[project]
name = "m3logpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Qmm", email = "1259598502@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
